# Generated by Django 2.2.5 on 2020-01-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20200108_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question_under',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='module_id',
            new_name='module_under',
        ),
    ]
