# Generated by Django 2.1.1 on 2020-02-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='module_under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.Module'),
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
